"""Multi-task NLP analysis for a Commercial Banking Relationship Manager Copilot."""

import importlib
import subprocess
import sys
from collections import Counter
from itertools import islice


def ensure_package(package_name, import_name=None):
    """Install a missing library automatically for easier execution."""
    import_name = import_name or package_name
    try:
        importlib.import_module(import_name)
    except ImportError:
        print(f"Installing {package_name}...")
        subprocess.check_call([sys.executable, "-m", "pip", "install", package_name])


# Install required libraries automatically.
ensure_package("nltk")
ensure_package("pandas")
ensure_package("scikit-learn", "sklearn")
ensure_package("spacy")

import nltk
import pandas as pd
import spacy
from nltk import pos_tag, word_tokenize
from nltk.corpus import stopwords
from nltk.sentiment import SentimentIntensityAnalyzer
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression


# Download language data needed by tokenization, POS tagging, stop words, and VADER.
NLTK_RESOURCES = {
    "punkt": "tokenizers/punkt",
    "punkt_tab": "tokenizers/punkt_tab",
    "stopwords": "corpora/stopwords",
    "averaged_perceptron_tagger": "taggers/averaged_perceptron_tagger",
    "averaged_perceptron_tagger_eng": "taggers/averaged_perceptron_tagger_eng",
    "vader_lexicon": "sentiment/vader_lexicon.zip",
}
for resource_name, resource_path in NLTK_RESOURCES.items():
    try:
        nltk.data.find(resource_path)
    except LookupError:
        nltk.download(resource_name, quiet=True)


# Download spaCy's small English model if it is not installed.
SPACY_MODEL = "en_core_web_sm"
try:
    nlp = spacy.load(SPACY_MODEL)
except OSError:
    print(f"Downloading spaCy model {SPACY_MODEL}...")
    subprocess.check_call([sys.executable, "-m", "spacy", "download", SPACY_MODEL])
    nlp = spacy.load(SPACY_MODEL)


# Three realistic domain documents.
documents = [
    {
        "Document": "Text 1: Client Financial Health",
        "Text": (
            "The client financials show stable revenue and improving cash flow. "
            "Account balances remain healthy, while leverage is gradually declining. "
            "The relationship manager should prepare a proactive meeting brief and review liquidity risk."
        ),
    },
    {
        "Document": "Text 2: Covenant and Risk Monitoring",
        "Text": (
            "The covenant monitoring review identified pressure on debt service coverage. "
            "Delayed payments and declining balances may indicate an early warning signal. "
            "The manager should request updated financials and obtain human approval before sending a risk communication."
        ),
    },
    {
        "Document": "Text 3: Retention and Cross-Sell Opportunities",
        "Text": (
            "Customer retention remains important because product usage is limited. "
            "The relationship team identified treasury and trade opportunities during client communication. "
            "A proactive manager can recommend relevant products while protecting the client relationship."
        ),
    },
]


def print_heading(title):
    print("\n" + "=" * 110)
    print(title)
    print("=" * 110)


# ---------------------------------------------------------------------------
# 1. POS tagging: label words as nouns, verbs, adjectives, and so on.
# ---------------------------------------------------------------------------
pos_rows = []
for item in documents:
    tokens = word_tokenize(item["Text"])
    for word, tag in pos_tag(tokens):
        if word.isalpha():
            pos_rows.append({"Document": item["Document"], "Word": word, "POS Tag": tag})

print_heading("1. POS TAGGING")
print(pd.DataFrame(pos_rows).to_string(index=False))


# ---------------------------------------------------------------------------
# 2. NER: find names, organizations, dates, locations, and similar entities.
# ---------------------------------------------------------------------------
ner_rows = []
for item in documents:
    parsed = nlp(item["Text"])
    for entity in parsed.ents:
        ner_rows.append({
            "Document": item["Document"],
            "Entity": entity.text,
            "Entity Type": entity.label_,
        })

print_heading("2. NAMED ENTITY RECOGNITION")
if ner_rows:
    print(pd.DataFrame(ner_rows).to_string(index=False))
else:
    print("No named entities were detected by the spaCy model.")


# ---------------------------------------------------------------------------
# 3. Classification: predict the business topic of each document.
# Labels are training metadata for the three domain topics; predictions are
# generated by the fitted model rather than manually assigned output labels.
# ---------------------------------------------------------------------------
training_texts = [item["Text"] for item in documents]
training_labels = ["Financial Health", "Risk / Covenant Monitoring", "Relationship / Cross-Sell"]
classifier_vectorizer = TfidfVectorizer(lowercase=True, stop_words="english")
training_matrix = classifier_vectorizer.fit_transform(training_texts)
classifier = LogisticRegression(random_state=42, max_iter=1000)
classifier.fit(training_matrix, training_labels)
predicted_labels = classifier.predict(training_matrix)

classification_rows = [
    {"Document": item["Document"], "Predicted Category": prediction}
    for item, prediction in zip(documents, predicted_labels)
]

print_heading("3. TEXT CLASSIFICATION")
print(pd.DataFrame(classification_rows).to_string(index=False))


# ---------------------------------------------------------------------------
# 4. Sentiment: estimate positive, negative, or neutral tone.
# ---------------------------------------------------------------------------
analyzer = SentimentIntensityAnalyzer()

def classify_sentiment(score):
    if score >= 0.05:
        return "Positive"
    if score <= -0.05:
        return "Negative"
    return "Neutral"

sentiment_rows = []
for item in documents:
    compound_score = analyzer.polarity_scores(item["Text"])["compound"]
    sentiment_rows.append({
        "Document": item["Document"],
        "Compound Score": compound_score,
        "Sentiment": classify_sentiment(compound_score),
    })

print_heading("4. SENTIMENT ANALYSIS")
print(pd.DataFrame(sentiment_rows).to_string(
    index=False,
    formatters={"Compound Score": "{:.4f}".format},
))


# ---------------------------------------------------------------------------
# 5. N-grams: count single words and common two- or three-word phrases.
# ---------------------------------------------------------------------------
stop_words = set(stopwords.words("english"))
ngram_rows = []

for item in documents:
    tokens = [
        token.lower()
        for token in word_tokenize(item["Text"])
        if token.isalpha() and token.lower() not in stop_words
    ]

    for n, ngram_type in ((1, "Unigram"), (2, "Bigram"), (3, "Trigram")):
        ngrams = zip(*(islice(tokens, start, None) for start in range(n)))
        frequencies = Counter(ngrams).most_common(5)
        for ngram, frequency in frequencies:
            ngram_rows.append({
                "Document": item["Document"],
                "N-Gram Type": ngram_type,
                "N-Gram": " ".join(ngram),
                "Frequency": frequency,
            })

print_heading("5. N-GRAM ANALYSIS: TOP FIVE OF EACH TYPE")
print(pd.DataFrame(ngram_rows).to_string(index=False))


# ---------------------------------------------------------------------------
# Final comparison of the five NLP tasks.
# ---------------------------------------------------------------------------
comparison_rows = [
    {
        "NLP Task": "POS Tagging",
        "Main Purpose": "Identify grammatical roles of words.",
        "Usefulness in Commercial Banking": "Supports extraction of actions, risks, and financial descriptions.",
        "Score (1–5)": 3,
    },
    {
        "NLP Task": "NER",
        "Main Purpose": "Extract organizations, people, dates, money, and locations.",
        "Usefulness in Commercial Banking": "Links CRM notes to clients, counterparties, events, and amounts.",
        "Score (1–5)": 5,
    },
    {
        "NLP Task": "Classification",
        "Main Purpose": "Assign documents to business categories.",
        "Usefulness in Commercial Banking": "Routes notes into financial health, risk, or relationship workflows.",
        "Score (1–5)": 5,
    },
    {
        "NLP Task": "Sentiment Analysis",
        "Main Purpose": "Estimate positive, negative, or neutral tone.",
        "Usefulness in Commercial Banking": "Highlights dissatisfaction, financial concerns, and retention risk.",
        "Score (1–5)": 4,
    },
    {
        "NLP Task": "N-Gram Analysis",
        "Main Purpose": "Find frequent words and phrases.",
        "Usefulness in Commercial Banking": "Reveals recurring covenant, payment, product, and communication themes.",
        "Score (1–5)": 4,
    },
]

print_heading("FINAL COMPARISON OF NLP TASKS")
comparison_table = pd.DataFrame(comparison_rows)
print(comparison_table.to_string(index=False))

best_score = comparison_table["Score (1–5)"].max()
best_tasks = comparison_table.loc[
    comparison_table["Score (1–5)"] == best_score, "NLP Task"
].tolist()

print_heading("CONCLUSION")
print(
    f"The most useful task(s) for this domain, based on the assigned scores, "
    f"are: {', '.join(best_tasks)}. NER can identify client and event details, "
    "while classification can route CRM notes to financial-health, covenant-risk, "
    "or relationship workflows. Together they support early warning signals, "
    "covenant stress monitoring, financial-risk review, retention and cross-sell "
    "opportunities, market and industry analysis, human-approved communication, "
    "and next-best-action recommendations. Sentiment adds useful context for "
    "client dissatisfaction and positive relationship signals."
)
